const $=x=>document.getElementById(x);let state;
(async()=>{state=await chrome.runtime.sendMessage({type:"getState"});$("ai").checked=state.settings.indexAi;$("web").checked=state.settings.indexWeb;$("webContent").checked=state.settings.indexWebContent;$("delay").value=String(state.settings.webIndexDelaySec||25);$("gem").checked=state.settings.geminiEnabled;$("key").value="";$("keyStatus").textContent=state.geminiKeyPresent?"מפתח Gemini מוגדר לסשן הנוכחי. כדי להחליף אותו, הזן מפתח חדש.":"מפתח Gemini לא מוגדר.";$("account").value=state.settings.importAccount||""})();
async function save(){const s={indexAi:$("ai").checked,indexWeb:$("web").checked,indexWebContent:$("webContent").checked,webIndexDelaySec:Number($("delay").value)||25,geminiEnabled:$("gem").checked,importAccount:$("account").value.trim()};if(s.indexWebContent){const have=await chrome.permissions.contains({origins:["http://*/*","https://*/*"]});if(!have){const ok=await chrome.permissions.request({origins:["http://*/*","https://*/*"]});if(!ok){$("webContent").checked=false;s.indexWebContent=false;alert("לא ניתנה הרשאת אתרים")}}}await chrome.runtime.sendMessage({type:"saveSettings",settings:s})}
for(const x of["ai","web","webContent","delay","gem","account"])$(x).addEventListener("change",save);
$("key").addEventListener("change",async()=>{const r=await chrome.runtime.sendMessage({type:"setGeminiKey",key:$("key").value});if(r.ok){$("key").value="";$("keyStatus").textContent="מפתח נשמר לסשן בלבד."}else $("keyStatus").textContent=r.error||"שגיאה"});
$("history").onclick=async()=>{$("status").textContent="מייבא…";const r=await chrome.runtime.sendMessage({type:"importHistory"});$("status").textContent=r.ok?"יובאו "+r.added+" רשומות.":"שגיאה: "+r.error};
$("export").onclick=async()=>{const r=await chrome.runtime.sendMessage({type:"exportIndex"}),b=new Blob([JSON.stringify(r.docs,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="ai-universal-search-index.json";a.click()};
$("clear").onclick=async()=>{if(confirm("למחוק את כל האינדקס?")){await chrome.runtime.sendMessage({type:"clear"});location.reload()}};
$("import").onclick=async()=>{const fs=[...$("files").files];if(!fs.length)return;$("status").textContent="מעבד…";let n=0;const mode=$("importMode").value,account=$("account").value.trim();for(const f of fs){try{const raw=await f.text(),kind=$("kind").value==="auto"?detect(raw,f.name):$("kind").value,docs=parseExport(raw,kind,account,f.name,/\.jsonl$/i.test(f.name),mode);if(docs.length){const r=await chrome.runtime.sendMessage({type:"importDocs",docs});n+=r.added||0}}catch(e){console.error(e)}}$("status").textContent="יובאו "+n+" רשומות."};
function detect(r,n){if(/conversation/i.test(n)||/"mapping"\s*:/.test(r))return"chatgpt";if(/chat_messages|claude/i.test(r))return"claude";if(/safeHtmlItem|gemini/i.test(r))return"gemini";return"aistudio"}
function aiTitle(source,title){const p={chatgpt:"CHATGPT",gemini:"GEMINI",aistudio:"AISTUDIO",claude:"CLAUDE"}[source];const t=String(title||"").trim();if(!p)return t;const re=new RegExp("^"+p+"\\s*-\\s*","i");return t&&!re.test(t)?p+"- "+t:t||p+"- שיחה"}
function fileTitle(name=""){return String(name||"").replace(/\.(jsonl?|txt|html?)$/i,"").replace(/[_-]+/g," ").trim()}
function makeConversation(k,account,c,index,fallbackTitle=""){const cid=c.id||c.uuid||c.conversationId||String(index);const fallback=k==="aistudio"?fileTitle(fallbackTitle):"";const title=aiTitle(k,c.title||c.name||fallback||({"gemini":"Gemini","aistudio":"AI Studio"}[k]||"שיחה מיובאת"));const date=c.createdAt||c.created_at||c.create_time||c.create_time_iso||"";return{id:"imp:"+hash([k,account,cid].join("|")),source:k,account,title,url:c.url||url(k),text:"",visitedAt:Date.parse(date)||Date.now(),kind:"conversation",conversationId:cid}}
function makeMessage(k,account,o,index){const text=String(o.text||"").trim();if(!text)return null;const title=aiTitle(k,o.title||"");return{id:"imp:"+hash([k,account,o.conversationId||"",o.messageId||index,text.slice(0,500)].join("|")),source:k,account,title:title||aiTitle(k,"שיחה מיובאת"),url:o.url||url(k),text:text.slice(0,200000),visitedAt:o.createdAt?Date.parse(o.createdAt)||Date.now():Date.now(),kind:"message",conversationId:o.conversationId||"",messageId:o.messageId||String(index)}}
function parseExport(raw,k,account,fileName="",jsonl=false,mode="titles"){if(jsonl){const out=[];for(const line of raw.split(/\r?\n/)){if(!line.trim())continue;try{out.push(...parseExport(line,k,account,fileName,false,mode))}catch{}}return out}let x;try{x=JSON.parse(raw)}catch{throw Error("JSON לא תקין")}const titlesOnly=mode!=="full";if(k==="chatgpt")return titlesOnly?chatgptTitles(x,k,account):chatgptFull(x,k,account);if(k==="claude")return titlesOnly?claudeTitles(x,k,account):claudeFull(x,k,account);if(k==="gemini"&&isGeminiTakeout(x))return titlesOnly?geminiTakeoutTitles(x,k,account):geminiTakeoutFull(x,k,account);return titlesOnly?genericTitles(x,k,account,fileName):genericFull(x,k,account,fileName)}
function listConversations(x){return Array.isArray(x)?x:(x.conversations||x.chats||x.data||[x])}
function geminiTakeoutEntries(x){return Array.isArray(x)?x:(Array.isArray(x?.data)?x.data:[])}
function isGeminiTakeout(x){return geminiTakeoutEntries(x).some(e=>/gemini\\.google\\.com\\/app\\/c\\//i.test(String(e?.titleUrl||e?.url||""))&&(Array.isArray(e?.details)||Array.isArray(e?.userInteractions)))}
function geminiConversationId(e,i){const u=String(e?.titleUrl||e?.url||"");const m=u.match(/\\/app\\/c\\/([^/?#]+)/i);return m?.[1]||("event:"+i)}
function geminiActivityParts(e){const out=[];if(Array.isArray(e?.details)){for(const d of e.details){const name=String(d?.name||"").toLowerCase();const text=String(d?.value||"").trim();if(text&&(name.includes("request")||name.includes("prompt")))out.push({role:"user",text});else if(text&&(name.includes("response")||name.includes("answer")))out.push({role:"assistant",text})}}if(Array.isArray(e?.userInteractions)){for(const w of e.userInteractions){const ui=w?.userInteraction||{};for(const role of ["request","response"]){const raw=ui?.[role];if(raw==null)continue;let text="";try{text=txt(JSON.parse(raw))}catch{text=String(raw)}text=String(text||"").trim();if(text)out.push({role:role==="request"?"user":"assistant",text})}}}if(e?.prompt||e?.response){if(e.prompt)out.push({role:"user",text:String(e.prompt).trim()});if(e.response)out.push({role:"assistant",text:String(e.response).trim()})}return out}
function geminiTakeoutGroups(x){const map=new Map();for(const[e,i]of geminiTakeoutEntries(x).map((e,i)=>[e,i])){const id=geminiConversationId(e,i);if(!map.has(id))map.set(id,[]);map.get(id).push(e)}return map}
function geminiTakeoutTitle(events){for(const e of events){const req=geminiActivityParts(e).find(p=>p.role==="user")?.text;if(req){const clean=req.replace(/\\s+/g," ").trim();return clean.length>120?clean.slice(0,117)+"…":clean}}return "שיחת Gemini"}
function geminiTakeoutTitles(x,k,account){const out=[];for(const[id,events]of geminiTakeoutGroups(x)){const first=events[0],title=aiTitle(k,geminiTakeoutTitle(events));out.push({id:"imp:"+hash([k,account,id].join("|")),source:k,account,title,url:String(first?.titleUrl||first?.url||url(k)),text:"",visitedAt:Date.parse(String(first?.time||""))||Date.now(),kind:"conversation",conversationId:id})}return out}
function geminiTakeoutFull(x,k,account){const out=[];for(const[id,events]of geminiTakeoutGroups(x)){const title=aiTitle(k,geminiTakeoutTitle(events));let n=0;for(const e of events){for(const part of geminiActivityParts(e)){const o=makeMessage(k,account,{conversationId:id,title,url:String(e?.titleUrl||e?.url||url(k)),messageId:String(e?.time||n)+":"+n,createdAt:e?.time,text:part.text},n++);if(o)out.push(o)}}}return out}
function chatgptTitles(x,k,account){return listConversations(x).map((c,i)=>makeConversation(k,account,c,i))}
function chatgptFull(x,k,account){const out=[];for(const c of listConversations(x)){for(const[id,v]of Object.entries(c.mapping||{})){const m=v?.message,p=m?.content?.parts;if(Array.isArray(p)){const o=makeMessage(k,account,{conversationId:c.id,title:c.title,url:"https://chatgpt.com/c/"+(c.id||""),messageId:m.id||id,createdAt:m.create_time?new Date(m.create_time*1000).toISOString():"",text:p.filter(z=>typeof z==="string").join("\n")},id);if(o)out.push(o)}}}return out}
function claudeTitles(x,k,account){return listConversations(x).map((c,i)=>makeConversation(k,account,c,i))}
function claudeFull(x,k,account){const out=[];for(const c of listConversations(x)){const ms=c.chat_messages||c.messages||c.conversation?.messages||[];for(const[i,m]of ms.entries()){const o=makeMessage(k,account,{conversationId:c.uuid||c.id,title:c.name||c.title,url:"https://claude.ai/",messageId:m.uuid||m.id||String(i),createdAt:m.created_at||m.createdAt,text:txt(m)},i);if(o)out.push(o)}}return out}
function genericTitles(x,k,account,fallbackTitle=""){return listConversations(x).map((c,i)=>makeConversation(k,account,c,i,fallbackTitle))}
function genericFull(x,k,account,fallbackTitle=""){const out=[];for(const c of listConversations(x)){const ms=c.entries||c.messages||c.turns||c.contents||c.history||[];if(Array.isArray(ms)&&ms.length){for(const[i,m]of ms.entries()){const o=makeMessage(k,account,{conversationId:c.id||c.uuid||c.conversationId,title:c.title||c.name||fileTitle(fallbackTitle),url:c.url||url(k),messageId:m.id||m.uuid||String(i),createdAt:m.create_time||m.createdAt||m.timestamp,text:txt(m)},i);if(o)out.push(o)}}else{const o=makeMessage(k,account,{conversationId:c.id||c.uuid||c.conversationId,title:c.title||c.name||fileTitle(fallbackTitle),url:c.url||url(k),messageId:c.id,text:txt(c)},0);if(o)out.push(o)}}return out}
function txt(m){if(typeof m==="string")return m;if(Array.isArray(m?.safeHtmlItem))return m.safeHtmlItem.map(x=>{const d=new DOMParser().parseFromString(String(x?.html||""),"text/html");return d.body?.innerText||""}).join("\n");if(typeof m?.text==="string")return m.text;if(m?.prompt||m?.response)return[m.prompt,m.response].filter(Boolean).join("\n");if(Array.isArray(m?.content))return m.content.map(x=>typeof x==="string"?x:x?.text||x?.parts?.map?.(p=>p.text||"").join("\n")||"").join("\n");if(Array.isArray(m?.parts))return m.parts.map(p=>typeof p==="string"?p:p?.text||"").join("\n");return""}
function url(k){return k==="chatgpt"?"https://chatgpt.com/":k==="claude"?"https://claude.ai/":k==="aistudio"?"https://aistudio.google.com/":"https://gemini.google.com/"}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
