const $=x=>document.getElementById(x);let state;
(async()=>{state=await chrome.runtime.sendMessage({type:"getState"});$("ai").checked=state.settings.indexAi;$("web").checked=state.settings.indexWeb;$("webContent").checked=state.settings.indexWebContent;$("delay").value=String(state.settings.webIndexDelaySec||25);$("gem").checked=state.settings.geminiEnabled;$("key").value="";$("keyStatus").textContent=state.geminiKeyPresent?"מפתח Gemini מוגדר לסשן הנוכחי. כדי להחליף אותו, הזן מפתח חדש.":"מפתח Gemini לא מוגדר.";$("account").value=state.settings.importAccount||""})();
async function save(){const s={indexAi:$("ai").checked,indexWeb:$("web").checked,indexWebContent:$("webContent").checked,webIndexDelaySec:Number($("delay").value)||25,geminiEnabled:$("gem").checked,importAccount:$("account").value.trim()};if(s.indexWebContent){const have=await chrome.permissions.contains({origins:["http://*/*","https://*/*"]});if(!have){const ok=await chrome.permissions.request({origins:["http://*/*","https://*/*"]});if(!ok){$("webContent").checked=false;s.indexWebContent=false;alert("לא ניתנה הרשאת אתרים")}}}await chrome.runtime.sendMessage({type:"saveSettings",settings:s})}
for(const x of["ai","web","webContent","delay","gem","account"])$(x).addEventListener("change",save);
$("key").addEventListener("change",async()=>{const r=await chrome.runtime.sendMessage({type:"setGeminiKey",key:$("key").value});if(r.ok){$("key").value="";$("keyStatus").textContent="מפתח נשמר לסשן בלבד."}else $("keyStatus").textContent=r.error||"שגיאה"});
$("history").onclick=async()=>{$("status").textContent="מייבא…";const r=await chrome.runtime.sendMessage({type:"importHistory"});$("status").textContent=r.ok?"יובאו "+r.added+" רשומות.":"שגיאה: "+r.error};
$("export").onclick=async()=>{const r=await chrome.runtime.sendMessage({type:"exportIndex"}),b=new Blob([JSON.stringify(r.docs,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="ai-universal-search-index.json";a.click()};
$("clear").onclick=async()=>{if(confirm("למחוק את כל האינדקס?")){await chrome.runtime.sendMessage({type:"clear"});location.reload()}};
$("import").onclick=async()=>{const fs=[...$("files").files];if(!fs.length)return;$("status").textContent="מעבד…";let n=0;const mode=$("importMode").value;for(const f of fs){try{const raw=await f.text(),kind=$("kind").value==="auto"?detect(raw,f.name):$("kind").value,docs=parseExport(raw,kind,$("account").value.trim(),/\.jsonl$/i.test(f.name),mode);n+=(await chrome.runtime.sendMessage({type:"importDocs",docs})).added}catch(e){console.error(e)}}$("status").textContent="יובאו "+n+" רשומות."};
function detect(r,n){if(/conversation/i.test(n)||/"mapping"\s*:/.test(r))return"chatgpt";if(/chat_messages|claude/i.test(r))return"claude";if(/safeHtmlItem|gemini/i.test(r))return"gemini";return"aistudio"}
function aiTitle(source,title){const p={chatgpt:"CHATGPT",gemini:"GEMINI",aistudio:"AISTUDIO",claude:"CLAUDE"}[source];const t=String(title||"").trim();if(!p)return t;const re=new RegExp("^"+p+"\\s*-\\s*","i");return t&&!re.test(t)?p+"- "+t:t||p+"- שיחה"}
function parseExport(raw,k,account,jsonl=false,mode="titles"){if(jsonl){const out=[];for(const line of raw.split(/\r?\n/)){if(!line.trim())continue;try{out.push(...parseExport(line,k,account,false,mode))}catch{}}return out}let x;try{x=JSON.parse(raw)}catch{throw Error("JSON לא תקין")}const titlesOnly=mode==="titles",out=[];
const addConversation=(c,index=0)=>{const title=aiTitle(k,c.title||c.name||({"gemini":"Gemini","aistudio":"AI Studio"}[k]||"שיחה מיובאת));const cid=c.id||c.uuid||c.conversationId||String(index);out.push({id:"imp:"+hash([k,account,cid].join("|")),source:k,account,title,url:c.url||url(k),text:"",visitedAt:Date.parse(c.createdAt||c.created_at||c.create_time||"")||Date.now(),kind:"conversation",conversationId:cid})};
const addMessage=(o,index=0)=>{const text=String(o.text||"").trim();if(!text)return;const title=aiTitle(k,o.title||"");out.push({id:"imp:"+hash([k,account,o.conversationId||"",o.messageId||index,text.slice(0,500)].join("|")),source:k,account,title:title||aiTitle(k,"שיחה מיובאת"),url:o.url||url(k),text:text.slice(0,200000),visitedAt:o.createdAt?Date.parse(o.createdAt)||Date.now():Date.now(),kind:"message",conversationId:o.conversationId||"",messageId:o.messageId||String(index)})};
if(k==="chatgpt")chatgpt(x,titlesOnly?addConversation:addMessage);else if(k==="claude")claude(x,titlesOnly?addConversation:addMessage);else generic(x,titlesOnly?addConversation:addMessage);return out}
function chatgpt(x,add){for(const c of(Array.isArray(x)?x:x.conversations||[]))add(c)}
function chatgptFull(x,a){for(const c of(Array.isArray(x)?x:x.conversations||[]))for(const[id,v]of Object.entries(c.mapping||{})){const m=v?.message,p=m?.content?.parts;if(Array.isArray(p))a({conversationId:c.id,title:c.title,url:"https://chatgpt.com/c/"+(c.id||""),messageId:m.id||id,createdAt:m.create_time?new Date(m.create_time*1000).toISOString():"",text:p.filter(z=>typeof z==="string").join("\n")})}}
function claude(x,add){const cs=Array.isArray(x)?x:x.conversations||x.chats||x.data||[];for(const c of cs){const ms=c.chat_messages||c.messages||c.conversation?.messages||[];if(add===addConversation){}add(c)}}
function claudeFull(x,a){const cs=Array.isArray(x)?x:x.conversations||x.chats||x.data||[];for(const c of cs){const ms=c.chat_messages||c.messages||c.conversation?.messages||[];for(const[i,m]of ms.entries())a({conversationId:c.uuid||c.id,title:c.name||c.title,url:"https://claude.ai/",messageId:m.uuid||m.id||String(i),createdAt:m.created_at||m.createdAt,text:txt(m)})}}
function generic(x,add){const cs=Array.isArray(x)?x:x.conversations||x.chats||x.data||[x];for(const c of cs)add(c)}
function genericFull(x,a){const cs=Array.isArray(x)?x:x.conversations||x.chats||x.data||[x];for(const c of cs){const ms=c.entries||c.messages||c.turns||c.contents||c.history||[];if(Array.isArray(ms)&&ms.length)for(const[i,m]of ms.entries())a({conversationId:c.id||c.uuid||c.conversationId,title:c.title||c.name,url:c.url||url("aistudio"),messageId:m.id||m.uuid||String(i),createdAt:m.create_time||m.createdAt||m.timestamp,text:txt(m)});else a({conversationId:c.id||c.uuid,title:c.title||c.name,url:c.url||url("aistudio"),messageId:c.id,text:txt(c)})}}
function txt(m){if(typeof m==="string")return m;if(Array.isArray(m?.safeHtmlItem))return m.safeHtmlItem.map(x=>{const d=new DOMParser().parseFromString(String(x?.html||""),"text/html");return d.body?.innerText||""}).join("\n");if(typeof m?.text==="string")return m.text;if(m?.prompt||m?.response)return[m.prompt,m.response].filter(Boolean).join("\n");if(Array.isArray(m?.content))return m.content.map(x=>typeof x==="string"?x:x?.text||x?.parts?.map?.(p=>p.text||"").join("\n")||"").join("\n");if(Array.isArray(m?.parts))return m.parts.map(p=>typeof p==="string"?p:p?.text||"").join("\n");return""}
function url(k){return k==="chatgpt"?"https://chatgpt.com/":k==="claude"?"https://claude.ai/":k==="aistudio"?"https://aistudio.google.com/":"https://gemini.google.com/"}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
