const $=id=>document.getElementById(id);let tab=null,ctx=null;
async function pageContext(){if(!tab?.id||!/^https?:$/.test(new URL(tab.url||"").protocol))throw Error("אין גישה לדף הזה");try{const r=await chrome.tabs.sendMessage(tab.id,{type:"getPageContext"});if(r?.ok)return r}catch{}const r=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>{const e=document.querySelector("main,article,[role=main]")||document.body;return{title:document.title,url:location.href,content:(e?.innerText||"").slice(0,50000)}}});return r?.[0]?.result||{}}
async function init(){const ts=await chrome.tabs.query({active:true,currentWindow:true});tab=ts[0];if(!tab?.url){$("status").textContent="לא נמצא דף פעיל";return}$("url").textContent=tab.url;let host="";try{host=new URL(tab.url).hostname}catch{}const r=await chrome.runtime.sendMessage({type:"getSite",url:tab.url});const site=r.site;$("name").value=site?.siteName||tab.title||host;$("desc").value=site?.siteDescription||"";}
$("save").onclick=async()=>{const r=await chrome.runtime.sendMessage({type:"saveSite",url:tab.url,siteName:$("name").value,siteDescription:$("desc").value});$("status").textContent=r.ok?"נשמר.":"שגיאה: "+r.error};
$("ai").onclick=async()=>{if(blockedUrl(tab.url)){ $("status").textContent="האתר מוחרג מטעמי פרטיות.";return}$("status").textContent="בודק פרטיות אתר…";try{const policy=await chrome.runtime.sendMessage({type:"getSitePolicy",url:tab.url});if(!policy.ok){throw Error(policy.error||"שגיאה בבדיקת האתר")}if(policy.blocked){$("status").textContent="האתר מוחרג מטעמי פרטיות.";return}$("status").textContent="AI מנתח את הדף…";ctx=ctx||await pageContext();if(!ctx?.content)throw Error("לא נמצא תוכן");const r=await chrome.runtime.sendMessage({type:"generateSiteMetadata",url:tab.url,title:ctx.title||tab.title,content:ctx.content});if(!r.ok)throw Error(r.error||"שגיאה");$("name").value=r.data.siteName||$("name").value;$("desc").value=r.data.siteDescription||$("desc").value;await chrome.runtime.sendMessage({type:"saveSite",url:tab.url,siteName:$("name").value,siteDescription:$("desc").value});$("status").textContent="השם והתיאור נוצרו ונשמרו עם AI."}catch(e){$("status").textContent=String(e.message||e)}};
$("indexNow").onclick=async()=>{try{const c=ctx||await pageContext();const u=new URL(tab.url);const source=/chatgpt\.com|chat\.openai\.com/.test(u.hostname)?"chatgpt":/gemini\.google\.com/.test(u.hostname)?"gemini":/aistudio\.google\.com/.test(u.hostname)?"aistudio":/claude\.ai/.test(u.hostname)?"claude":"web";const r=await chrome.runtime.sendMessage({type:"saveDoc",incognito:!!tab.incognito,doc:{id:"page:"+u.origin+u.pathname,source,title:tab.title||c.title,url:tab.url,text:c.content||"",visitedAt:Date.now(),kind:"page"}});$("status").textContent=r.ok?"הדף הוכנס לאינדקס.":"לא ניתן להכניס: "+(r.reason||r.error||"בדוק שהפעלת אינדקס Web")}catch(e){$("status").textContent=String(e.message||e)}};
$("readLater").onclick=async()=>{try{const r=await chrome.runtime.sendMessage({type:"addReadLater",url:tab.url,title:tab.title,incognito:!!tab.incognito});if(!r.ok)throw Error(r.error||r.reason||"שגיאה");await chrome.tabs.remove(tab.id);window.close()}catch(e){$("status").textContent=String(e.message||e)}};
$("deleteHistory").onclick=async()=>{if(!confirm("Chrome תמחק את כל המופעים של הכתובת הזו מההיסטוריה. להמשיך?"))return;const r=await chrome.runtime.sendMessage({type:"deleteHistory",url:tab.url});$("status").textContent=r.ok?"הכתובת נמחקה מהיסטוריית Chrome.":"שגיאה: "+r.error};
$("openSearch").onclick=async()=>{try{await chrome.sidePanel.open({windowId:tab.windowId});window.close()}catch{chrome.runtime.openOptionsPage()}};
$("close").onclick=()=>window.close();init();