const $=id=>document.getElementById(id);let tab=null,ctx=null;
const blocked=["mail.google.com","drive.google.com","docs.google.com","web.whatsapp.com","bankhapoalim.co.il","leumi.co.il"];
function blockedUrl(u){try{const h=new URL(u).hostname.replace(/^www\./,"");return blocked.some(x=>h===x||h.endsWith("."+x))}catch{return true}}
async function pageContext(){if(!tab?.id||!/^https?:$/.test(new URL(tab.url||"").protocol))throw Error("אין גישה לדף הזה");try{const r=await chrome.tabs.sendMessage(tab.id,{type:"getPageContext"});if(r?.ok)return r}catch{}const r=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>{const e=document.querySelector("main,article,[role=main]")||document.body;return{title:document.title,url:location.href,content:(e?.innerText||"").slice(0,50000)}}});return r?.[0]?.result||{}}
async function init(){const ts=await chrome.tabs.query({active:true,currentWindow:true});tab=ts[0];if(!tab?.url){$("status").textContent="לא נמצא דף פעיל";return}$("url").textContent=tab.url;const r=await chrome.runtime.sendMessage({type:"getSite",url:tab.url});const site=r.site;$("name").value=site?.siteName||tab.title||new URL(tab.url).hostname;$("desc").value=site?.siteDescription||"";ctx=await pageContext().catch(()=>null);if(!ctx)$("status").textContent="לא ניתן לקרוא את תוכן הדף; עדיין אפשר לשמור שם ותיאור ידנית."}
$("save").onclick=async()=>{const r=await chrome.runtime.sendMessage({type:"saveSite",url:tab.url,siteName:$("name").value,siteDescription:$("desc").value});$("status").textContent=r.ok?"נשמר.":"שגיאה: "+r.error};
$("ai").onclick=async()=>{if(blockedUrl(tab.url)){ $("status").textContent="האתר מוחרג מטעמי פרטיות.";return}$("status").textContent="AI מנתח את הדף…";try{ctx=ctx||await pageContext();if(!ctx?.content)throw Error("לא נמצא תוכן");const r=await chrome.runtime.sendMessage({type:"generateSiteMetadata",url:tab.url,title:ctx.title||tab.title,content:ctx.content});if(!r.ok)throw Error(r.error||"שגיאה");$("name").value=r.data.siteName||$("name").value;$("desc").value=r.data.siteDescription||$("desc").value;await chrome.runtime.sendMessage({type:"saveSite",url:tab.url,siteName:$("name").value,siteDescription:$("desc").value});$("status").textContent="השם והתיאור נוצרו ונשמרו עם AI."}catch(e){$("status").textContent=String(e.message||e)}};
$("indexNow").onclick=async()=>{try{const c=ctx||await pageContext();const r=await chrome.runtime.sendMessage({type:"saveDoc",doc:{id:"page:"+new URL(tab.url).origin+new URL(tab.url).pathname,source:"web",title:tab.title||c.title,url:tab.url,text:c.content||"",visitedAt:Date.now(),kind:"page"}});$("status").textContent=r.ok?"הדף הוכנס לאינדקס.":"לא ניתן להכניס: "+(r.reason||r.error||"בדוק שהפעלת אינדקס Web")}catch(e){$("status").textContent=String(e.message||e)}};
$("readLater").onclick=async()=>{try{const r=await chrome.runtime.sendMessage({type:"addReadLater",url:tab.url,title:tab.title});if(!r.ok)throw Error(r.error||r.reason||"שגיאה");await chrome.tabs.remove(tab.id);window.close()}catch(e){$("status").textContent=String(e.message||e)}};
$("deleteHistory").onclick=async()=>{if(!confirm("Chrome תמחק את כל המופעים של הכתובת הזו מההיסטוריה. להמשיך?"))return;const r=await chrome.runtime.sendMessage({type:"deleteHistory",url:tab.url});$("status").textContent=r.ok?"הכתובת נמחקה מהיסטוריית Chrome.":"שגיאה: "+r.error};
$("openSearch").onclick=async()=>{try{await chrome.sidePanel.open({windowId:tab.windowId});window.close()}catch{chrome.runtime.openOptionsPage()}};
$("close").onclick=()=>window.close();init();