const $=id=>document.getElementById(id);let state={};
(async()=>{state=await chrome.runtime.sendMessage({type:"getState"});$("smart").checked=!!state.settings.geminiEnabled;$("laterCount").textContent=state.readLaterCount||0;$("q").placeholder="חיפוש ב-"+state.count+" פריטים…";})();
$("settings").onclick=()=>chrome.runtime.openOptionsPage();
$("clear").onclick=async()=>{if(confirm("למחוק את כל האינדקס המקומי?")){await chrome.runtime.sendMessage({type:"clear"});render([])}};
$("tabSearch").onclick=()=>showTab(true);$("tabLater").onclick=()=>showTab(false);
$("go").onclick=search;$("q").onkeydown=e=>{if(e.key==="Enter")search()};
async function search(){const q=$("q").value.trim();if(!q)return;$("status").textContent="מחפש…";const r=await chrome.runtime.sendMessage({type:"search",query:q,source:$("filter").value,smart:$("smart").checked,rerank:$("rankAi").checked});$("status").textContent=(r.smart?"חיפוש מורחב · ":"")+(r.ranked?"AI מִיֵּן · ":"")+"נמצאו "+(r.results?.length||0)+" תוצאות"+($("rankAi").checked?" — שים לב: התוכן שנשלח ל-AI מוגבל לתוצאות המובילות":"");render(r.results||[],q)}
async function showTab(searchTab){$("tabSearch").classList.toggle("tabActive",searchTab);$("tabLater").classList.toggle("tabActive",!searchTab);$("searchBox").style.display=searchTab?"block":"none";$("results").innerHTML="";$("filter").style.display=searchTab?"block":"none";if(searchTab)return;const r=await chrome.runtime.sendMessage({type:"getReadLater"});$("laterCount").textContent=r.items.length;renderLater(r.items)}
function render(arr,q=""){const root=$("results");root.innerHTML="";if(!arr.length){root.innerHTML='<div class="empty">לא נמצאו תוצאות</div>';return}for(const d of arr){const e=document.createElement("div");e.className="result";const desc=d.siteDescription?'<div class="desc">'+esc(d.siteDescription)+'</div>':"";const name=d.source==="web"?(d.siteName||d.title):(d.title||"ללא כותרת");e.innerHTML='<div class="meta">'+esc(d.source)+" · "+esc(d.account||"")+' · '+new Date(d.visitedAt||d.updatedAt||Date.now()).toLocaleString("he-IL")+'</div><div class="title">'+esc(name)+'</div>'+desc+(d.source==="web"&&d.title&&d.title!==name?'<div class="pageTitle">'+esc(d.title)+'</div>':"")+'<div class="snippet">'+esc(snippet(d.text||"",q))+'</div><div class="row"><button class="open">פתח</button><button class="later">לקרוא אח״כ</button><button class="del">הסר</button></div>';e.querySelector(".open").onclick=()=>chrome.tabs.create({url:d.url});e.querySelector(".later").onclick=async()=>{const r=await chrome.runtime.sendMessage({type:"addReadLater",url:d.url,title:d.title,incognito:false});if(r.ok){state.readLaterCount=(state.readLaterCount||0)+1;$("laterCount").textContent=state.readLaterCount}};e.querySelector(".del").onclick=async()=>{await chrome.runtime.sendMessage({type:"deleteDoc",id:d.id});search()};root.appendChild(e)}}
function renderLater(items){const root=$("results");root.innerHTML="";if(!items.length){root.innerHTML='<div class="empty">אין כרגע פריטים ב״לקרוא אח״כ״</div>';return}const clear=document.createElement("div");clear.className="row";clear.innerHTML='<button class="danger">מחק את כל הרשימה</button>';clear.querySelector("button").onclick=async()=>{if(confirm("למחוק את כל רשימת ״לקרוא אח״כ״?")){await chrome.runtime.sendMessage({type:"clearReadLater"});showTab(false)}};root.appendChild(clear)for(const x of items){const e=document.createElement("div");e.className="later";e.innerHTML='<div class="meta">'+new Date(x.addedAt||Date.now()).toLocaleString("he-IL")+'</div><div class="title">'+esc(x.siteName||x.title||x.url)+'</div>'+(x.siteDescription?'<div class="desc">'+esc(x.siteDescription)+'</div>':"")+'<div class="pageTitle">'+esc(x.title||"")+'</div><div class="row"><button class="open">פתח</button><button class="del">הסר</button></div>';e.querySelector(".open").onclick=()=>chrome.tabs.create({url:x.url});e.querySelector(".del").onclick=async()=>{await chrome.runtime.sendMessage({type:"deleteReadLater",id:x.id});showTab(false)};root.appendChild(e)}}
function snippet(t,q){t=t.replace(/\s+/g," ").trim();const x=q.replace(/"([^"]+)"/g," $1 ").split(/\s+/).find(z=>z.length>2&&!z.includes(":")&&!z.startsWith("-"));const p=x?Math.max(0,t.toLowerCase().indexOf(x.toLowerCase())-180):0;return t.slice(p,p+700)}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}